### ISSUE TITLE
Slow HTTP communication causing delays

### ISSUE THREAD

**Issue by raamdev** [websharks/html-compressor#13]
In the Quick Cache integration of HTML Compressor, I'm noticing that sometimes there will be long (15+ second) delays the first time the HTML Compressor grabs remote resources for compression.

```
<!-- Quick Cache HTML Compressor took: 16.50146 seconds -->
```

@JasWSInc wrote...

> The only that comes to mind is the HTTP communication. If there is an external resource responding slowly it could exhibit this behavior you've described, and given the nature of the HTML Compressor this would speed up on each page view because it only visits the external resources once in most cases.
> 
> Yes, if you can open an issue in the HTML Compressor repo for this I'll take a closer look. To start with it might be helpful for us to have more to go on than just the overall time. I'd like to integrate some additional timers to show us which specific remote connections may have caused the delay.

I think it would be great if the HTML Compressor could detect when the entire compression process took longer than X number of seconds (maybe longer than 5 seconds) and then reported exactly what took so long... i.e., fetching what resources caused the delay.

**Comment by lkraav** [comment]
Not trying to gravedig here, but looking to figure out if a new issues is in order. I experienced pretty strange PHP process zombification right now on a relatively high traffic site where as soon as you Empty Cache, the site becomes completely unresponsive, and non-ending PHP processes start piling up, effectively causing a DoS shortly after.

After lengthy debugging and process of eliminating, I ended up disabling "include remote resources" and it seems we are in complete stable land thereafter.

I `strace`-d some of the hanging PHP processes. They were stuck on an `flock()` call, which lead me to think about disable the remote resource fetching. Not many plugins need to `flock()` things but `zencache-pro` is one of them. My hypothesis is that it may be possible for a busy site to DoS itself when the remote resources cannot be fetched quickly enough with the first cache priming page load, which makes all other page loads also start fetching them. This would explain a bunch of zombie PHP processes piling up like I saw.

Thoughts?

**Comment by raamdev** [comment]
@lkraav What version of PHP is this and what server OS?

**Comment by lkraav** [comment]
This is on 5.5.14, CentOS 6. I'm thinking about having the support upgrade the PHP to latest 5.6 anyway. But could this be something PHP version specific?

**Comment by raamdev** [comment]
@lkraav It could be, but I'm not sure. 

@jaswsinc do you have any thoughts here?

**Comment by jaswsinc** [comment]
> My hypothesis is that it may be possible for a busy site to DoS itself when the remote resources cannot be fetched quickly enough with the first cache priming page load, which makes all other page loads also start fetching them. This would explain a bunch of zombie PHP processes piling up like I saw.

I think that's worth testing, yes. It's a very complex issue to discuss in chat; i.e., I find it hard to illustrate to someone how `flock()` actually works, but the hypothesis you have sounds interesting. If another PHP process is attempting to cache the same page while waiting for remote resources to load, that could impact the parent code in ZenCache that is holding a lock open while it waits.

Referencing: https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/closures/Ac/ObUtils.php#L260-L289

The whole idea of locking is to prevent two processes from overlapping. However, in this case we have the potential for a remote site to cause other ZenCache processes to wait for an existing lock to be released before it will continue. This line is blocking on purpose, but perhaps we can change that. Referencing: https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/closures/Ac/ObUtils.php#L260
