### ISSUE TITLE
Incompatibility with some Lightbox effects (and Firefox ?)

### ISSUE THREAD

**Issue by Li-An** [websharks/html-compressor#42]
Hello,
it worked nice before but with WP 4.0 PrettyPhoto from Responsive Lightbox https://wordpress.org/plugins/responsive-lightbox/ do not work anymore (it works with WP 3.9 as I've got a WP 3.9 still using both) in Firefox (seems to work with Chrome).
Same problem with https://wordpress.org/plugins/simple-lightbox/
The two effects manages original size of images (they do not resize them so they fit to the screen).

**Comment by jaswsinc** [comment]
Resolved by: https://github.com/websharks/html-compressor/issues/66
~ Coming in a future release of both the HTML Compressor and ZenCache Pro.
