### ISSUE TITLE
Enable WebSharks™ HTML Compression

### ISSUE THREAD

**Issue by LittleBastard77** [websharks/html-compressor#51]
I am using the latest version of quick cache pro to date and wordpress 4.

I enabled HTML compression last night with default options. Some tests showed improvement in speed. However this afternoon the site was extremely slow to the point that I got alerts that it was offline.

I opened a ticket with support and they sent me this. After struggling renaming the quick cache plugin directory back and forth so I could disconnect users and get the speed needed to avoid a timeout I was able to disable the HTML compression and all got back to normal again.

The supportsperson sent me the data below (I changed some names on the data for safety). If you need more detailed information, please, be very specific so I can relay the request to support or even get the log files from cpanel myself. 

Thanks.

root@host [/usr/local/apache/domlogs]# w
11:01:45 up 13 days, 11:31, 1 user, load average: 7.66, 6.68, 5.65

This is due to PHP executing for EXAMPLE.com:

nobody 5907 1.8 0.3 104888 44112 ? Sl 09:09 2:04 \_ litespeed (lshttpd)
cpanelaccount 13645 10.4 0.7 213984 86244 ? S 10:55 0:38 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13673 18.2 0.7 214448 86376 ? S 10:56 0:55 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13762 11.5 0.7 214380 86712 ? S 10:58 0:24 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13765 4.3 0.6 211824 85596 ? S 10:58 0:09 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13840 13.3 0.7 212608 86448 ? S 10:59 0:20 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13842 29.1 0.7 217224 88568 ? S 10:59 0:42 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13858 6.7 0.7 213144 86688 ? S 10:59 0:07 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13924 14.9 0.7 212888 86628 ? S 11:00 0:14 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13989 7.7 0.7 214176 88428 ? S 11:00 0:07 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13990 46.6 0.6 213432 85488 ? S 11:00 0:42 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13991 9.8 0.7 215216 88588 ? S 11:00 0:08 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13992 8.0 0.7 217140 91368 ? S 11:00 0:06 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13994 17.7 0.7 213912 88148 ? S 11:00 0:14 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14009 9.7 0.7 214888 87916 ? S 11:00 0:06 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14014 12.4 0.7 221348 94932 ? S 11:00 0:07 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14016 5.0 0.7 213660 87896 ? S 11:00 0:02 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14020 13.3 0.8 234968 108008 ? R 11:00 0:06 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14028 5.1 0.7 212940 86828 ? S 11:01 0:02 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14263 4.9 0.6 212100 85848 ? S 11:01 0:01 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14264 14.2 0.7 212988 86320 ? S 11:01 0:04 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14267 12.8 0.6 211908 85600 ? S 11:01 0:02 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14320 11.5 0.6 211356 84840 ? S 11:01 0:01 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14325 15.6 0.6 212176 84996 ? S 11:01 0:00 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14329 42.0 0.6 212644 85996 ? S 11:01 0:01 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14330 45.6 0.6 211400 85016 ? S 11:01 0:01 | \_ lsphp5:/home/cpanelaccount/public_html/index.php

When I strace one of these running PHP processes, it appears that the Quick Cache plugin is causing problems. The processes are frequently waiting for a mutex lock created by this plugin.

**Comment by raamdev** [comment]
@LittleBastard77 This sounds like a Quick Cache issue. The HTML Compressor is a feature of the Quick Cache plugin, but since you're running Quick Cache, this issue should be filed on the Quick Cache repo: https://github.com/websharks/quick-cache/issues This HTML Compressor repo is meant for people who are running the HTML Compressor standalone, without Quick Cache.

Would you mind reopening this issue under the Quick Cache repo so that we can help you with it?

**Comment by LittleBastard77** [comment]
no. That's ok. Thanks.

2015-01-04 18:49 GMT-02:00 Raam Dev <notifications@github.com>:

**Comment by LittleBastard77** [comment]
There was a link pointing exactly where I reported it on the plugin
configs. Maybe you would like to look at that.

2015-01-04 18:57 GMT-02:00 Marcelo Ribeiro <marcelo@hiperciencia.com>:

**Comment by raamdev** [comment]
> There was a link pointing exactly where I reported it on the plugin
> configs. Maybe you would like to look at that.

I'm not sure what you mean by this. Could you please explain?

**Comment by LittleBastard77** [comment]
I reported where the plugin suggested me to on the "report issues her
<https://github.com/websharks/html-compressor/issues>e"

Attached.

2015-01-04 19:06 GMT-02:00 Raam Dev <notifications@github.com>:

**Comment by raamdev** [comment]
@LittleBastard77 Thank you. I'm sorry for the confusion. I will make sure that link gets updated in the next release.

In your original message, it says:

> The processes are frequently waiting for a mutex lock created by this plugin.

That tells me it's not a problem specific to the HTML Compressor but rather a problem with the Quick Cache plugin itself. Have you updated to the latest version of the plugin (v141231)? We fixed several bugs related to file locking.

**Comment by LittleBastard77** [comment]
Yes, 141231.

2015-01-04 19:15 GMT-02:00 Raam Dev <notifications@github.com>:

**Comment by raamdev** [comment]
> Yes, 141231.

Thank you. I've gone ahead and moved this issue to the Quick Cache repo: https://github.com/websharks/quick-cache/issues/391

Please follow that issue for further updates.
