### ISSUE TITLE
Vary: Accept-Encoding

### ISSUE THREAD

**Issue by jaswsinc** [websharks/html-compressor#55]
Referencing: https://github.com/websharks/zencache/issues/436

The HTML Compressor could auto-generate an `.htaccess` file in its public cache directory that includes Apache-compatible rules for this header, so as to avoid being penalized by tools like Pingdom and GTMetrix.

**Comment by jaswsinc** [comment]
The `.htaccess` file that the latest release of the HTML Compressor creates in the public HTML Compressor cache directory. Referencing: https://github.com/websharks/zencache/issues/436

```apache
<IfModule authz_core_module>
	Require all granted
</IfModule>
<IfModule !authz_core_module>
	allow from all
</IfModule>

<IfModule headers_module>
	<FilesMatch "\.(html|js|css)$">
		Header append Vary: Accept-Encoding
	</FilesMatch>
</IfModule>
```

cc @raamdev

**Comment by raamdev** [comment]
@jaswsinc Awesome. Thanks!
