### ISSUE TITLE
HTML minification

### ISSUE THREAD

**Issue by szepeviktor** [websharks/html-compressor#56]
Good morning!

Do you suggest to use your `compress_html()` function for *as quickly as possible* **standalone** HTML minification?
I am building a PageSpeed 100/100 tool.

**Comment by jaswsinc** [comment]
@szepeviktor writes...
> Do you suggest to use your compress_html() function for as quickly as possible standalone HTML minification?

Certainly. I see no problem using it that. You'll find instructions in the README.md file with an example of how to call it on arbitrary HTML.

See: https://github.com/websharks/html-compressor#3-html-compressor-on-raw-html-code

**Comment by szepeviktor** [comment]
Thank you!
When do you plan to get ready with testing?
#53

**Comment by jaswsinc** [comment]
The HTML Compressor has already been tested quite a bit through the Quick Cache and ZenCache plugins for WordPress; i.e., it has been out-in-the-wild for almost a year.

However, we are working to build a full test suite for the HTML Compressor soon. Most likely within the next month or two. See: https://github.com/websharks/html-compressor/issues/53
