### ISSUE TITLE
HTML Compression and 'Market' theme - combining JS & CSS from head & body problems

### ISSUE THREAD

**Issue by superian** [websharks/html-compressor#57]
The theme's home page is rohitink.com/2014/03/13/market/ and the free version is at wordpress.org/themes/market/ - it's the latter I've tried.

If 'combine JS from (head) into fewer files' is enabled, the main menu does not work properly: mousing over it does not reveal submenu details.

If 'combine CSS from (head) and (body) into fewer files' is enabled, the theme is totally broken visually. 

Other settings are ok to enable.

**Comment by superian** [comment]
I've found another one this applies to, but it's not publicly available. Would you like a copy?

**Comment by jaswsinc** [comment]
> The theme's home page is rohitink.com/2014/03/13/market/ and the free version is at wordpress.org/themes/market/ - it's the latter I've tried.

Very sorry for the delayed response here! I will test this theme just as soon as I can. We are working on some improvements in the HTML Compressor now, so this issue will hopefully be resolved in the next day or two.

**Comment by jaswsinc** [comment]
It is likely that this issue will have been resolved by one or both of these recent fixes:

- https://github.com/websharks/html-compressor/issues/65
- https://github.com/websharks/html-compressor/issues/66

~ Leaving this open for testing in order to confirm that being the case.

**Comment by jaswsinc** [comment]
Confirmed. This has been resolved by work in other issues.
~ The next release of the HTML Compressor is coming soon in a future release of ZenCache Pro.

![2015-08-21_00-04-58](https://cloud.githubusercontent.com/assets/1563559/9404029/4a7e1cd6-4798-11e5-8b1f-16bb37156b84.png)
