### ISSUE TITLE
Feature Request: JSON Compression

### ISSUE THREAD

**Issue by raamdev** [websharks/html-compressor#59]
See https://github.com/websharks/zencache/issues/469

> The HTML Compressor currently only supports compressing/minifying HTML, CSS, and JavaScript. It would be nice to also support JSON (which appears to only require removing whitespace).
>
> If you want to enable [Google Sitelinks Search Box](https://developers.google.com/structured-data/slsb-overview) on your site, you need to add a snippet of JSON that uses `<script type="application/ld+json"></script>` (see https://github.com/websharks/zencache/issues/467 for a full example). It would be nice if the ZenCache HTML Compressor could also compress this.

**Comment by jaswsinc** [comment]
_Also compress `type="application/json"`_

**Comment by jaswsinc** [comment]
_Or any `type="*json*"` for that matter._

**Comment by jaswsinc** [comment]
Added in v150424. https://github.com/websharks/html-compressor/releases/tag/150424
