### ISSUE TITLE
SSL Checks (Bug In Scheme Detection)

### ISSUE THREAD

**Issue by jaswsinc** [websharks/html-compressor#61]
We should probably update this line of code to force a specific data type. At present, this is assuming `SERVER_PORT` will be a string, but if a server is setting the value to an integer it might be causing some trouble. https://github.com/websharks/html-compressor/blob/150512/src/includes/classes/Core.php#L2861

A similar issue here. This could also look for a boolean-ish true value.
https://github.com/websharks/html-compressor/blob/150512/src/includes/classes/Core.php#L2866
e.g., `if(filter_var($_SERVER['HTTPS'], FILTER_VALIDATE_BOOLEAN))`

**Comment by raamdev** [comment]
Referencing internal ticket that led to this issue: https://websharks.zendesk.com/agent/tickets/7319

**Comment by jaswsinc** [comment]
Done. Coming in the next release.

**Comment by raamdev** [comment]
Woohoo!

**Comment by raamdev** [comment]
@jaswsinc I noticed there was no changelog entry for this issue here: https://github.com/websharks/html-compressor/releases

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** Improved strict data type comparison when analyzing `$_SERVER` environment variables to detect an `https://` connection URL. We now detect `(integer)443` and `(string)443`. In addition, we can now pick up `$_SERVER['HTTPS']` being any of `1|on|yes|true` (caSe insensitive).

**Comment by raamdev** [comment]
**ZenCache Pro v150821** has been released and includes changes from this GitHub Issue.

See the [ZenCache Pro v150821 announcement](http://zencache.com/zencache-pro-v150821-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#61).
