### ISSUE TITLE
Minification Problem with CSS Pseudo-Classes

### ISSUE THREAD

**Issue by jaswsinc** [websharks/html-compressor#66]
A copy of: https://github.com/websharks/zencache/issues/544

Reference: https://webshark.zendesk.com/agent/tickets/7790

CSS pseudo-classes require a space between the class-name and pseudo-class-name. When minifying CSS with ZenCache, that space is removed, breaking the code.

For example:

`.test :first-child { color: green; }` would be changed to `.test:first-child{color:green;}`

## Work-Around to Avoid This Issue

To avoid this issue, choose "No, do not compress the code in any unified CSS files" from the panel at **WordPress Dashboard → ZenCache → Plugin Options → HTML Compression**. 

![zencache-screenshot](https://cloud.githubusercontent.com/assets/9320495/9215141/aec914f0-4074-11e5-90c6-e238064951c4.jpg)

**Comment by lkraav** [comment]
`.test :first-child` and `.test:first-child` are two different things, but both are valid.

The issue description currently reads like the space is always required, which it isn't.

**Comment by jaswsinc** [comment]
I'm considering the use of [this library](http://leafo.github.io/scssphp/) to help us achieve a better-er-er, more standards-compliant compression for CSS. cc @raamdev ~ http://leafo.github.io/scssphp/

**Comment by raamdev** [comment]
> http://leafo.github.io/scssphp/

@jaswsinc That looks like an SCSS compiler, not specifically a CSS compressor. Does it support straight CSS compression? I looked through the docs but everything seems to indicate starting with SCSS and then outputting compressed CSS.

**Comment by jaswsinc** [comment]
> Does it support straight CSS compression?

Yes. Sure does!

It's an SCSS library, and Sass (SCSS) is the most modern way of dealing with CSS compression. The SCSS syntax itself is such that any valid CSS file (i.e., something that we would be compressing), is also a valid SCSS file.

> The new main syntax (as of Sass 3) is known as “SCSS” (for “Sassy CSS”), and is a superset of CSS3's syntax. This means that every valid CSS3 stylesheet is valid SCSS as well. SCSS files use the extension .scss. The second, older syntax is known as the indented syntax (or just “Sass”).

Over the past year or so I have been using SCSS almost exclusively in new projects, and I just finished converting ZenCache to SCSS also. The `--style=compressed` output format supported by SCSS compilers (including this one written in PHP) should be a perfect fit for the HTML Compressor.

**Comment by jaswsinc** [comment]
Referencing: http://leafo.github.io/scssphp/docs/#output-formatting

**Comment by raamdev** [comment]
> The SCSS syntax itself is such that any valid CSS file (i.e., something that we would be compressing), is also a valid SCSS file.

Fascinating! Thanks! I'll have to dig into SCSS a bit more.

**Comment by jaswsinc** [comment]
Closing. Resolved by: https://github.com/websharks/css-minifier/issues/1
~ Coming in a future release of ZenCache.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- Resolves a bug related to CSS pseudo selectors `:` and whitespace. See [this GitHub issue](https://github.com/websharks/html-compressor/issues/66) if you'd like additional details.
