### ISSUE TITLE
Remote Connection Failures

### ISSUE THREAD

**Issue by jaswsinc** [websharks/html-compressor#69]
A fork of: https://github.com/websharks/zencache/issues/391 where a ZenCache user reports that a mutex lock is taking longer than expected in some cases, and the suspicion is that this is related to hanging HTTP processes that take longer than expected on some hosts.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- Improved HTTP connection handling, timeouts, protocol, BOM markers, exceptions, `Referer:` and `User-Agent:` headers. See: websharks/html-compressor#69 for details. See also: https://github.com/websharks/zencache/issues/391

**Comment by jaswsinc** [comment]
cc @raamdev

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#69).
