### ISSUE TITLE
REQUEST_SCHEME http Over SSL?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/html-compressor#73]
I have at least one report of `$_SERVER['REQUEST_SCHEME']` being set to `http` on GoDaddy servers whenever the current request is actually over `https` and `$_SERVER['HTTPS'] === 'on'`. This creates a problem in the HTML Compressor as reported here internally: https://websharks.zendesk.com/agent/tickets/8461

cc @raamdev

**Comment by jaswsinc** [comment]
## Next Actions

- Comment [these lines](https://github.com/websharks/html-compressor/blob/150821/src/includes/classes/Core.php#L3049-L3051) so that we are detecting SSL only. The `REQUEST_SCHEME` is not absolutely necessary there, and since we now know it is unreliable on some shared hosts, we can just comment this block out.

**Comment by raamdev** [comment]
@jaswsinc Can you confirm if https://github.com/websharks/zencache/issues/413 and https://github.com/websharks/zencache/issues/348 both look related to this issue?

**Comment by jaswsinc** [comment]
@raamdev Hard to say for sure, but definitely sounds like the same sort of thing.

**Comment by raamdev** [comment]
@jaswsinc In both of those issues, the use had "just switched from http to https" on their entire site, which sounds to me like it could have exposed this bug. https://github.com/websharks/zencache/issues/413 talks about CDN, but that could have been a coincidence.

**Comment by jaswsinc** [comment]
I agree. It sounds like this could have been the underlying cause.

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#73).
