### ISSUE TITLE
why not concat and compress js files?

### ISSUE THREAD

**Issue by guzuomuse** [websharks/html-compressor#79]
i'm using the version 160118

php framework yii2 
everything is ok but the javascript files not concat and compress?
i try for a long time but can't get it work
how to set the js_exclusions?
i found this [topic](https://cometcache.com/kb-article/why-doesnt-the-html-compressor-compress-all-css-javascript/) but nothing help me  :(
thank you

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the source code, detailed bug reports, and feature requests. Customer service and technical support are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket
