### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by mucahitnezir** [websharks/html-compressor#81]
When i want to download this project via composer, i got error. Please fix it.

**Comment by raamdev** [comment]
@mucahitnezir What error?

**Comment by mucahitnezir** [comment]
![webshark-html-compressor-error](https://user-images.githubusercontent.com/9297972/26854506-1c39f75a-4b1f-11e7-97e8-e351d6d8e6dc.png)

**Comment by jaswrks** [comment]
@mucahitnezir Please add this line to your `composer.json`.
This package requires dev-state dependencies.

```json
"minimum-stability": "dev",
```

**Comment by jaswrks** [comment]
See also: https://getcomposer.org/doc/04-schema.md#minimum-stability
